package com.cloupia.feature.storage.nonTabularReports;

import com.cloupia.feature.storage.constants.StorageConstants;
import com.cloupia.model.cIM.DynReportContext;
import com.cloupia.model.cIM.ReportContextRegistry;
import com.cloupia.model.cIM.ReportDefinition;
import com.cloupia.service.cIM.inframgr.reportengine.ContextMapRule;
import com.cloupia.service.cIM.inframgr.reports.simplified.CloupiaNonTabularReport;

/**
 * This is the first part of developing a bar chart report.  The second part you should
 * look in BarChartReportImpl.java.  For the most part everything resembles a plain tabular
 * report but there are a couple of important things to mention:
 * 
 * 1. Extend CloupiaNonTabularReport.
 * 2. getReportType need to return REPORT_TYPE_SNAPSHOT
 * 3. getReportHint need to return REPORT_HINT_BARCHART
 *
 */
public class BarChartReport extends CloupiaNonTabularReport {
	
	private static final String NAME = "storageModule.bar.chart.report";
	private static final String LABEL = "Bar Chart";
	
   /**
    * @return BarChartReport implementation class type 
    */
	@Override
	public Class getImplementationClass() {
		return BarChartReportImpl.class;
	}
	/**
	 * @return Report label
	 */
	@Override
	public String getReportLabel() {
		return LABEL;
	}
    /**
     * @return report name
     */
	@Override
	public String getReportName() {
		return NAME;
	}
    /**
     * @return true only if the report implementation followed POJO approach 
     */
	@Override
	public boolean isEasyReport() {
		return false;
	}
    /**
     * @return true if the report does not have any drillDown report
     */
	@Override
	public boolean isLeafReport() {
		return true;
	}
	/** 
	 * @return report type like tabular report,snapshot report ,summary report etc.
	 */
	@Override
	public int getReportType() {
		return ReportDefinition.REPORT_TYPE_SNAPSHOT;
	}
	/** 
	 * @return report hint
	 */
	@Override
	public int getReportHint()
	{
		return ReportDefinition.REPORT_HINT_BARCHART;
	}
	
	/**
	*@return true if you want this chart to show up in a summary report
	*/
	@Override
	public boolean showInSummary()
	{
		return true;
	}
	
	/**
	 * Defines under which menu the report should be shown in UI
	 * @return returns menu Id
	 */
	@Override
	public int getMenuID() {
		return StorageConstants.PHYSICAL_STORAGE_MENU;
	}
	
	/**
	 * Defines the report context map rule
	 * @return returns map rule
	 */
	@Override
	public ContextMapRule[] getMapRules() {
		//i'm using an autogenerated report context (which I registered in FooModule), as mentioned in documentation
		//the type may vary depending on deployments, so the safest way to retrieve the auto generated type value
		//is to use the getContextByName api!
		DynReportContext dummyContextOneType = ReportContextRegistry.getInstance().getContextByName(StorageConstants.INFRA_ACCOUNT_TYPE);
		ContextMapRule rule = new ContextMapRule();
		rule.setContextName(dummyContextOneType.getId());
		rule.setContextType(dummyContextOneType.getType());
		
		ContextMapRule[] rules = new ContextMapRule[1];
		rules[0] = rule;
		
		return rules;
	}

}
