package com.cloupia.feature.storage.nonTabularReports;

import com.cloupia.feature.storage.constants.StorageConstants;
import com.cloupia.model.cIM.DynReportContext;
import com.cloupia.model.cIM.ReportContextRegistry;
import com.cloupia.model.cIM.ReportDefinition;
import com.cloupia.service.cIM.inframgr.reportengine.ContextMapRule;
import com.cloupia.service.cIM.inframgr.reports.simplified.CloupiaNonTabularReport;

/**
 * This demonstrates how you can utilize the form framework to build a form in the space of a report.
 * We call forms that consume the space of an entire tab in the UI (normally reserved for reports), config forms.
 * This looks like very similar to a report action but there are a couple of important things to notice:
 * 
 * 1. Extend CloupiaNonTabularReport
 * 2. getReportType returns REPORT_TYPE_CONFIG_FORM
 * 3. isManagementReport returns true
 *
 */
public class FormReport extends CloupiaNonTabularReport {
	
	private static final String NAME = "storageModule.form.report";
	private static final String LABEL = "Form Report";

	@Override
	public Class getImplementationClass() {
		return FormReportAction.class;
	}
	
	@Override
	public String getReportLabel() {
		return LABEL;
	}

	@Override
	public String getReportName() {
		return NAME;
	}

	//If your form implementation uses CloupiaReportAction, then you need to specify it is an easy report
	//otherwise, the framework assumes you know what you are doing and are building a form with our low level APIs!
	@Override
	public boolean isEasyReport() {
		return true;
	}

	@Override
	public boolean isLeafReport() {
		return true;
	}
	
	//Make sure to return the proper report type
	@Override
	public int getReportType() {
		return ReportDefinition.REPORT_TYPE_CONFIG_FORM;
	}
	
	//Make sure this returns true, if you return false, the UI will not show your form!
	@Override
	public boolean isManagementReport()
	{
		return true;
	}
	
	/**
	 * Defines under which menu the report should be shown in UI
	 * @return returns menu Id
	 */
	@Override
	public int getMenuID() {
		return StorageConstants.PHYSICAL_STORAGE_MENU;
	}
	
	/**
	 * Defines the report context map rule
	 * @return returns map rule
	 */
	@Override
	public ContextMapRule[] getMapRules() {
		//i'm using an autogenerated report context (which I registered in FooModule), as mentioned in documentation
		//the type may vary depending on deployments, so the safest way to retrieve the auto generated type value
		//is to use the getContextByName api!
		DynReportContext dummyContextOneType = ReportContextRegistry.getInstance().getContextByName(StorageConstants.INFRA_ACCOUNT_TYPE);
		ContextMapRule rule = new ContextMapRule();
		rule.setContextName(dummyContextOneType.getId());
		rule.setContextType(dummyContextOneType.getType());
		
		ContextMapRule[] rules = new ContextMapRule[1];
		rules[0] = rule;
		
		return rules;
	}

}
