package com.cloupia.feature.storage.nonTabularReports;

import com.cloupia.feature.storage.constants.StorageConstants;
import com.cloupia.model.cIM.DynReportContext;
import com.cloupia.model.cIM.ReportContextRegistry;
import com.cloupia.model.cIM.ReportDefinition;
import com.cloupia.service.cIM.inframgr.reportengine.ContextMapRule;
import com.cloupia.service.cIM.inframgr.reports.simplified.CloupiaNonTabularReport;

/**
 * This is the first part of developing a pie chart report.  The second part you should
 * look in PieChartReportImpl.java.  For the most part everything resembles a plain tabular
 * report but there are a couple of important things to mention:
 * 
 * 1. Extend CloupiaNonTabularReport.
 * 2. getReportType need to return REPORT_TYPE_SNAPSHOT
 * 3. getReportHint need to return REPORT_HINT_PIECHART
 *
 */
public class PieChartReport extends CloupiaNonTabularReport {
	
	private static final String NAME = "storageModule.pie.chart.report";
	private static final String LABEL = "Pie Chart";

	/**
	 * Provides report implementation class
	 * @return : report implementation class
	 */
	@Override
	public Class getImplementationClass() {
		return PieChartReportImpl.class;
	}
	
	/**
	 * Report label which will be shown in UI
	 * @return report label
	 */
	@Override
	public String getReportLabel() {
		return LABEL;
	}

	/**
	 * Report name should be unique accross UCSD
	 * @return report name
	 */
	@Override
	public String getReportName() {
		return NAME;
	}

	/**
	 * Specifies wheather report is Easy report(POJO based)
	 * @return boolean value: true if easy report
	 */
	@Override
	public boolean isEasyReport() {
		return false;
	}

	/**
	 * Specifies wheather report has any child report
	 * @return boolean value: true if report has child report
	 */
	@Override
	public boolean isLeafReport() {
		return true;
	}
	
	/**
	 * Specifies report type e.g. historical, summary, snapshot etc
	 * @return report type
	 */
	@Override
	public int getReportType() {
		return ReportDefinition.REPORT_TYPE_SNAPSHOT;
	}
	
	/**
	 * Specifies report hint e.g. Bar chart, Pie Chart, Plot chart etc
	 * @return report hint
	 */
	@Override
	public int getReportHint()
	{
		return ReportDefinition.REPORT_HINT_PIECHART;
	}
	
	/**
	 * Defines under which menu the report should be shown in UI
	 * @return returns menu Id
	 */
	@Override
	public int getMenuID() {
		return StorageConstants.PHYSICAL_STORAGE_MENU;
	}
	
	/**
	 * Defines the report context map rule
	 * @return returns map rule
	 */
	@Override
	public ContextMapRule[] getMapRules() {
		//i'm using an autogenerated report context (which I registered in FooModule), as mentioned in documentation
		//the type may vary depending on deployments, so the safest way to retrieve the auto generated type value
		//is to use the getContextByName api!
		DynReportContext dummyContextOneType = ReportContextRegistry.getInstance().getContextByName(StorageConstants.INFRA_ACCOUNT_TYPE);
		ContextMapRule rule = new ContextMapRule();
		rule.setContextName(dummyContextOneType.getId());
		rule.setContextType(dummyContextOneType.getType());
		
		ContextMapRule[] rules = new ContextMapRule[1];
		rules[0] = rule;
		
		return rules;
	}

}
